/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiClass;

import DAO.DATA;
import java.awt.Color;
import javax.swing.JOptionPane;
import OOP.Users.Kurir;
import java.awt.HeadlessException;
import java.sql.SQLException;

/**
 *
 * @author roni
 */
public class DialogEditTambahKurir extends javax.swing.JDialog {

    /**
     * Creates new form DialogEditTambahKurir
     */
    Kurir kurir;
    public DialogEditTambahKurir(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        initComponents();
        if (parent.getClass().getName().equals("GuiClass.GUIMenuKurir")){
            kurir = (Kurir) DATA.listAkun.stream().filter(t -> t.getKode().equals(GUIMenuKurir.kurir.getKode())).findFirst().orElse(null);
            tfUsername.setText(kurir.getUsername());
            tfPassword.setText(kurir.getPassword());
            tfNoTelepon.setText(kurir.getNoHp());
            tfKota.setText(kurir.getKota());
            tfUsername.setForeground(Color.BLACK);
            tfPassword.setForeground(Color.BLACK);
            tfNoTelepon.setForeground(Color.BLACK);
            tfKota.setForeground(Color.BLACK);
            jLabel1.setText("Edit Profil");
            jButton1.setText("Edit");
        } else if (GUIMenuAdmin.btnEdit.getModel().isArmed()){
            tfUsername.setText(GUIMenuAdmin.getTableValue(1));
            tfPassword.setText(GUIMenuAdmin.getTableValue(2));
            tfNoTelepon.setText(GUIMenuAdmin.getTableValue(3));
            tfKota.setText(GUIMenuAdmin.getTableValue(4));
            tfUsername.setForeground(Color.BLACK);
            tfPassword.setForeground(Color.BLACK);
            tfNoTelepon.setForeground(Color.BLACK);
            tfKota.setForeground(Color.BLACK);
            jLabel1.setText("Edit Kurir");
            jButton1.setText("Edit");
            kurir = (Kurir) DATA.listAkun.stream().filter(t -> t.getKode().equals(GUIMenuAdmin.jTable1.getValueAt(GUIMenuAdmin.jTable1.getSelectedRow(), 0))).findFirst().orElse(null);
        } else if(GUIMenuAdmin.btnTambahKurir.getModel().isArmed()) {
            jLabel1.setText("Tambah Kurir");
            jButton1.setText("Tambah");
            kurir = new Kurir(null,"","", "","WAITING FOR PACCKAGE","");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lUsername = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        lPassword = new javax.swing.JLabel();
        tfPassword = new javax.swing.JPasswordField();
        lNoTelepon = new javax.swing.JLabel();
        tfNoTelepon = new javax.swing.JTextField();
        lKota = new javax.swing.JLabel();
        tfKota = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("-??- KURIR");

        lUsername.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lUsername.setText("Username");

        tfUsername.setForeground(java.awt.Color.gray);
        tfUsername.setText("ex: Robert213");
        tfUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfUsernameFocusLost(evt);
            }
        });
        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });

        lPassword.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lPassword.setText("Password");

        tfPassword.setForeground(java.awt.Color.gray);
        tfPassword.setText("ex: 123qweASD");
        tfPassword.setEchoChar('\u0000');
        tfPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPasswordFocusLost(evt);
            }
        });
        tfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPasswordActionPerformed(evt);
            }
        });

        lNoTelepon.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lNoTelepon.setText("Nomor Telepon");

        tfNoTelepon.setForeground(java.awt.Color.gray);
        tfNoTelepon.setText("ex: 081234567890");
        tfNoTelepon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNoTeleponFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNoTeleponFocusLost(evt);
            }
        });
        tfNoTelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNoTeleponActionPerformed(evt);
            }
        });

        lKota.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lKota.setText("Kota kurir :");

        tfKota.setForeground(java.awt.Color.gray);
        tfKota.setText("ex: Bandung");
        tfKota.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfKotaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfKotaFocusLost(evt);
            }
        });

        jButton1.setText("Edit/Tambahkan");
        jButton1.setToolTipText("");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(lPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(lKota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lNoTelepon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNoTelepon, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(tfUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(tfPassword)
                            .addComponent(tfKota))))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNoTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNoTelepon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfKota)
                    .addComponent(lKota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(146, 146, 146)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(40, 40, 40))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUsernameFocusGained
        // TODO add your handling code here:
        if (tfUsername.getForeground()==Color.GRAY){
            tfUsername.setText("");
            tfUsername.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tfUsernameFocusGained

    private void tfUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUsernameFocusLost
        // TODO add your handling code here:
        if (tfUsername.getText().equals("")){
            tfUsername.setText("ex: Robert213");
            tfUsername.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_tfUsernameFocusLost

    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsernameActionPerformed

    private void tfPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPasswordFocusGained
        // TODO add your handling code here:
        if (tfPassword.getForeground()==Color.GRAY){
            tfPassword.setText("");
            tfPassword.setForeground(Color.BLACK);
            tfPassword.setEchoChar('●');
        }
    }//GEN-LAST:event_tfPasswordFocusGained

    private void tfPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPasswordFocusLost
        // TODO add your handling code here:
        if (tfPassword.getText().equals("")){
            tfPassword.setText("ex: 123qweASD");
            tfPassword.setForeground(Color.GRAY);
            tfPassword.setEchoChar((char)0);
        }
    }//GEN-LAST:event_tfPasswordFocusLost

    private void tfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPasswordActionPerformed

    private void tfNoTeleponFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNoTeleponFocusGained
        // TODO add your handling code here:
        if (tfNoTelepon.getForeground()==Color.GRAY){
            tfNoTelepon.setText("");
            tfNoTelepon.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tfNoTeleponFocusGained

    private void tfNoTeleponFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNoTeleponFocusLost
        // TODO add your handling code here:
        if (tfNoTelepon.getText().equals("")){
            tfNoTelepon.setText("ex: 081234567890");
            tfNoTelepon.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_tfNoTeleponFocusLost

    private void tfNoTeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNoTeleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNoTeleponActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(tfUsername.getForeground()==Color.BLACK&&
            tfPassword.getForeground()==Color.BLACK&&
            tfNoTelepon.getForeground()==Color.BLACK&&
            tfKota.getForeground()==Color.BLACK)
        {
            try {
                kurir.setUsername(tfUsername.getText());
                kurir.setPassword(tfPassword.getText());
                kurir.setNoHp(tfNoTelepon.getText());
                kurir.setKota(tfKota.getText());
                DATA.updateDATA(kurir);
                assert (tfNoTelepon.getText()).matches("\\d{10,13}") : JOptionPane.showOptionDialog(null, "Nomor Telepon tidak valid", "Message", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
                assert (tfPassword.getText()).length()>=8 : JOptionPane.showOptionDialog(null, "Password kurang dari 8", "Message", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
                assert DATA.listGudang.stream().anyMatch(t -> tfKota.getText().toLowerCase().contains(t.getKota().toLowerCase())) : JOptionPane.showOptionDialog(null, "Layanan belum tersedia di kota anda", "Message", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
                if (!jLabel1.getText().toLowerCase().contains("edit")){
                    assert !DATA.listAkun.stream().anyMatch(t -> t instanceof Kurir && t.getUsername().equalsIgnoreCase(tfUsername.getText())) : JOptionPane.showOptionDialog(null, "Username sudah ada", "Message", JOptionPane.INFORMATION_MESSAGE, JOptionPane.INFORMATION_MESSAGE, null, null, null);
                    DATA.addDATA(kurir);
                }
                switch (jLabel1.getText()) {
                    case "Edit Kurir":
                        JOptionPane.showMessageDialog(this, "Berhasil diperbarui");
                        GUIMenuAdmin.showTable();
                        break;
                    case "Tambah Kurir":
                        JOptionPane.showMessageDialog(this, "Berhasil ditambah");
                        GUIMenuAdmin.showTable();
                        break;
                    case "Edit Profil":
                        JOptionPane.showMessageDialog(this, "Berhasil diperbarui");
                        GUILogin.tfUsername.setText(kurir.getUsername());
                        GUILogin.tfPassword1.setText(kurir.getPassword());
                        GUIMenuKurir.jLabel1.setText("Selamat datang, "+kurir.getUsername());
                        GUIMenuKurir.loadData();
                        break;
                }
                dispose();
            } catch (NullPointerException | HeadlessException | SQLException ex) {
                JOptionPane.showMessageDialog(this, "Terjadi Kesalahan");
            } catch (AssertionError e){}
        } else {
            JOptionPane.showMessageDialog(this, "Format salah atau belum diisi");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfKotaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfKotaFocusGained
        // TODO add your handling code here:
        if (tfKota.getForeground()==Color.GRAY){
            tfKota.setText("");
            tfKota.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tfKotaFocusGained

    private void tfKotaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfKotaFocusLost
        // TODO add your handling code here:
        if (tfKota.getText().equals("")){
            tfKota.setText("ex: Bandung");
            tfKota.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_tfKotaFocusLost

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DialogEditTambahKurir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(() -> {
//            try {
//                DialogEditTambahKurir dialog = new DialogEditTambahKurir(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            } catch (SQLException ex) {
//                Logger.getLogger(DialogEditTambahKurir.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lKota;
    private javax.swing.JLabel lNoTelepon;
    private javax.swing.JLabel lPassword;
    private javax.swing.JLabel lUsername;
    private javax.swing.JTextField tfKota;
    private javax.swing.JTextField tfNoTelepon;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
