/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiClass;

import DAO.DATA;
import static DAO.Factory.*;
import OOP.Misc.Pembayaran;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author roni
 */
public class DialogPembayaran extends javax.swing.JDialog {

    /**
     * Creates new form DialogPembayaran
     */
    ArrayList<Pembayaran> listPembayaran = new ArrayList<>();
    Pembayaran pembayaran;
    
    public DialogPembayaran(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        initComponents();
        DATA.loadDATA();
        listPembayaran = DATA.payment;
        lHargaPaket.setText("-Rp."+(GUIMenuPengirim.pengirim.getPaket().get(GUIMenuPengirim.tableCount).hargaBarang()+GUIMenuPengirim.pengirim.getPaket().get(GUIMenuPengirim.tableCount).hargaPajak()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lNoRekening = new javax.swing.JLabel();
        tfNoRekening = new javax.swing.JTextField();
        tfPin = new javax.swing.JPasswordField();
        lPin = new javax.swing.JLabel();
        lSaldo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lHargaPaket = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        lNoRekening.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lNoRekening.setText("No Rekening");

        tfNoRekening.setForeground(java.awt.Color.gray);
        tfNoRekening.setText("Masukkan Nomor Rekening");
        tfNoRekening.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNoRekeningFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNoRekeningFocusLost(evt);
            }
        });
        tfNoRekening.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNoRekeningActionPerformed(evt);
            }
        });
        tfNoRekening.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNoRekeningKeyReleased(evt);
            }
        });

        tfPin.setForeground(java.awt.Color.gray);
        tfPin.setText("Masukkan PIN ATM");
        tfPin.setEchoChar('\u0000');
        tfPin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPinFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPinFocusLost(evt);
            }
        });
        tfPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPinActionPerformed(evt);
            }
        });

        lPin.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lPin.setText("PIN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lNoRekening, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfNoRekening)
                    .addComponent(tfPin, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lNoRekening, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfNoRekening, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfPin)
                    .addComponent(lPin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lSaldo.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lSaldo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lSaldo.setText("Rp. 0,-");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BAYAR");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Total Saldo");

        jButton1.setText("Bayar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lHargaPaket.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lHargaPaket.setText("harga paket");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lHargaPaket, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lHargaPaket))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(239, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfNoRekeningFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNoRekeningFocusGained
        // TODO add your handling code here:
        if (tfNoRekening.getText().equals("Masukkan Nomor Rekening")){
            tfNoRekening.setText("");
            tfNoRekening.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tfNoRekeningFocusGained

    private void tfNoRekeningFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNoRekeningFocusLost
        // TODO add your handling code here:
        if (tfNoRekening.getText().equals("")){
            tfNoRekening.setText("Masukkan Nomor Rekening");
            tfNoRekening.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_tfNoRekeningFocusLost

    private void tfNoRekeningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNoRekeningActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNoRekeningActionPerformed

    private void tfPinFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPinFocusGained
        // TODO add your handling code here:
        if (tfPin.getText().equals("Masukkan PIN ATM")){
            tfPin.setText("");
            tfPin.setForeground(Color.BLACK);
            tfPin.setEchoChar('●');
        }
    }//GEN-LAST:event_tfPinFocusGained

    private void tfPinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPinFocusLost
        // TODO add your handling code here:
        if (tfPin.getText().equals("")){
            tfPin.setText("Masukkan PIN ATM");
            tfPin.setForeground(Color.GRAY);
            tfPin.setEchoChar((char)0);
        }
    }//GEN-LAST:event_tfPinFocusLost

    private void tfPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPinActionPerformed

    private void tfNoRekeningKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNoRekeningKeyReleased
        // TODO add your handling code here:
        if(listPembayaran.stream().anyMatch((t) -> t.getNoKartu().equals(tfNoRekening.getText()))){
            pembayaran = listPembayaran.stream().filter((t) -> t.getNoKartu().equals(tfNoRekening.getText())).findFirst().orElse(null);
            lSaldo.setText(lSaldo.getText().replace("0,-", pembayaran.getSaldo()+""));
        } else {
            lSaldo.setText("Rp. 0,-");
        }
    }//GEN-LAST:event_tfNoRekeningKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            if(listPembayaran.stream().anyMatch((t) -> t.getNoKartu().equals(tfNoRekening.getText())&&t.getPin().equals(tfPin.getText()))){
                if (pembayaran.getSaldo()-(GUIMenuPengirim.pengirim.getPaket().get(GUIMenuPengirim.tableCount).hargaBarang()+GUIMenuPengirim.pengirim.getPaket().get(GUIMenuPengirim.tableCount).hargaPajak())<0){
                    throw new Exception("Uang tidak cukup");
                }
                getPembayaranDAO().updateBalance(pembayaran.getNoKartu(), pembayaran.getSaldo()-(GUIMenuPengirim.pengirim.getPaket().get(GUIMenuPengirim.tableCount).hargaBarang()+GUIMenuPengirim.pengirim.getPaket().get(GUIMenuPengirim.tableCount).hargaPajak()));
                DATA.loadDATA();
                JOptionPane.showMessageDialog(this, "Berhasil Dibayar");
                GUIMenuPengirim.pengirim.getPaket().get(GUIMenuPengirim.tableCount).setStatus("WAITING");
                DATA.updateDATA(GUIMenuPengirim.pengirim.getPaket().get(GUIMenuPengirim.tableCount));
                GUIMenuPengirim.showTable();
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Format nomor rekening atau pin salah/kosong");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Kesalahan transaksi");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DialogPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(() -> {
//            try {
//                DialogPembayaran dialog = new DialogPembayaran(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            } catch (SQLException ex) {
//                Logger.getLogger(DialogPembayaran.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lHargaPaket;
    private javax.swing.JLabel lNoRekening;
    private javax.swing.JLabel lPin;
    private javax.swing.JLabel lSaldo;
    public static javax.swing.JTextField tfNoRekening;
    public static javax.swing.JPasswordField tfPin;
    // End of variables declaration//GEN-END:variables
}
