/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiClass;

import DAO.DATA;
import OOP.Misc.Gudang;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.awt.HeadlessException;
import java.sql.SQLException;

/**
 *
 * @author roni
 */
public class DialogEditTambahGudang extends javax.swing.JDialog {

    /**
     * Creates new form DialogEditTambahKurir
     */
    Gudang gudang;
    
    public DialogEditTambahGudang(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        initComponents();
        if (GUIMenuAdmin.btnEditGudang.getModel().isArmed()){
        tfKota.setText(DATA.listGudang.get(GUIMenuAdmin.ltGudang.getSelectedIndex()).getKota());
        tfKota.setForeground(Color.BLACK);
        jLabel1.setText("Edit Gudang");
        jButton1.setText("Edit");
        gudang = DATA.listGudang.stream().filter(t -> t.getKota().equals(DATA.listGudang.get(GUIMenuAdmin.ltGudang.getSelectedIndex()).getKota())).findFirst().orElse(null);
        } else if(GUIMenuAdmin.btnTambahGudang.getModel().isArmed()) {
            jLabel1.setText("Tambah Gudang");
            jButton1.setText("Tambah");
            gudang = new Gudang(null, "");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lKota = new javax.swing.JLabel();
        tfKota = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("-??- Gudang");

        lKota.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lKota.setText("Cabang kota :");

        tfKota.setForeground(java.awt.Color.gray);
        tfKota.setText("ex: Bandung");
        tfKota.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfKotaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfKotaFocusLost(evt);
            }
        });

        jButton1.setText("Edit/Tambahkan");
        jButton1.setToolTipText("");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lKota, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(tfKota, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfKota)
                    .addComponent(lKota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(tfKota.getForeground()==Color.BLACK)
        {
            try {
                gudang.setKota(tfKota.getText());
                DATA.updateDATA(gudang);
                if (jLabel1.getText().equals("Edit Gudang")){
                    JOptionPane.showMessageDialog(this, "Berhasil diperbarui");
                } else if(jLabel1.getText().equals("Tambah Gudang")) {
                    JOptionPane.showMessageDialog(this, "Berhasil ditambah");
                }
                GUIMenuAdmin.showTable();
                GUIMenuAdmin.showList();
                dispose();
            } catch (HeadlessException | SQLException ex) {
                JOptionPane.showMessageDialog(this, "Terjadi Kesalahan");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Format salah atau belum diisi");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfKotaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfKotaFocusGained
        // TODO add your handling code here:
        if (tfKota.getForeground()==Color.GRAY){
            tfKota.setText("");
            tfKota.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tfKotaFocusGained

    private void tfKotaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfKotaFocusLost
        // TODO add your handling code here:
        if (tfKota.getText().equals("")){
            tfKota.setText("ex: Bandung");
            tfKota.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_tfKotaFocusLost

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DialogEditTambahGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(() -> {
//            try {
//                DialogEditTambahGudang dialog = new DialogEditTambahGudang(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            } catch (SQLException ex) {
//                Logger.getLogger(DialogEditTambahGudang.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lKota;
    private javax.swing.JTextField tfKota;
    // End of variables declaration//GEN-END:variables
}
