/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiClass;

import DAO.DATA;
import OOP.Users.Pengirim;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author roni
 */
public class DialogEditDaftarPengirim extends javax.swing.JDialog {
    
    /**
     * Creates new form DialogEditUser
     * @param parent
     * @param modal
     */
    Pengirim pengirim;
    java.awt.Frame parent;
    public DialogEditDaftarPengirim(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        this.parent = parent;
        initComponents();
        DATA.loadDATA();
        switch (parent.getClass().getName()) {
            case "GuiClass.StartMenu":
                jLabel1.setText("Register User");
                jButton1.setText("Daftar");
                pengirim = new Pengirim(null, "", "", "", "");
                break;
            case "GuiClass.GUIMenuAdmin":
                pengirim = (Pengirim) DATA.listAkun.stream().filter(t -> t.getKode().equals(GUIMenuAdmin.getTableValue(0))).findFirst().orElse(null);
                tfUsername.setText(GUIMenuAdmin.getTableValue(1));
                tfPassword.setText(GUIMenuAdmin.getTableValue(2));
                tfNoTelepon.setText(GUIMenuAdmin.getTableValue(3));
                taAlamat.setText(GUIMenuAdmin.getTableValue(4));
                tfUsername.setForeground(Color.BLACK);
                tfPassword.setForeground(Color.BLACK);
                tfNoTelepon.setForeground(Color.BLACK);
                taAlamat.setForeground(Color.BLACK);
                jLabel1.setText("Edit User");
                jButton1.setText("Edit");
                break;
            case "GuiClass.GUIMenuPengirim":
                pengirim = (Pengirim) DATA.listAkun.stream().filter(t -> t.getKode().equals(GUIMenuPengirim.pengirim.getKode())).findFirst().orElse(null);
                tfUsername.setText(GUIMenuPengirim.pengirim.getUsername());
                tfPassword.setText(GUIMenuPengirim.pengirim.getPassword());
                tfNoTelepon.setText(GUIMenuPengirim.pengirim.getNoHp());
                taAlamat.setText(GUIMenuPengirim.pengirim.getAlamat());
                tfUsername.setForeground(Color.BLACK);
                tfPassword.setForeground(Color.BLACK);
                tfNoTelepon.setForeground(Color.BLACK);
                taAlamat.setForeground(Color.BLACK);
                jLabel1.setText("Edit Profil");
                jButton1.setText("Edit");
                break;
            default:
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfNoTelepon = new javax.swing.JTextField();
        lAlamat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAlamat = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        lUsername = new javax.swing.JLabel();
        tfPassword = new javax.swing.JPasswordField();
        lPassword = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lNoTelepon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tfNoTelepon.setForeground(java.awt.Color.gray);
        tfNoTelepon.setText("ex: 081234567890");
        tfNoTelepon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNoTeleponFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNoTeleponFocusLost(evt);
            }
        });
        tfNoTelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNoTeleponActionPerformed(evt);
            }
        });

        lAlamat.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lAlamat.setText("Alamat");

        taAlamat.setColumns(20);
        taAlamat.setForeground(java.awt.Color.gray);
        taAlamat.setLineWrap(true);
        taAlamat.setRows(5);
        taAlamat.setText("ex: Jalan Buah Batu No.02, RT 09 RW 06, Lengkong, Bojongsoang");
        taAlamat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                taAlamatFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                taAlamatFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(taAlamat);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("-??- USER");

        tfUsername.setForeground(java.awt.Color.gray);
        tfUsername.setText("ex: Robert213");
        tfUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfUsernameFocusLost(evt);
            }
        });
        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });

        lUsername.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lUsername.setText("Username");

        tfPassword.setForeground(java.awt.Color.gray);
        tfPassword.setText("ex: 123qweASD");
        tfPassword.setEchoChar('\u0000');
        tfPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPasswordFocusLost(evt);
            }
        });
        tfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPasswordActionPerformed(evt);
            }
        });

        lPassword.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lPassword.setText("Password");

        jButton1.setText("Daftar/Edit");
        jButton1.setToolTipText("");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lNoTelepon.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lNoTelepon.setText("Nomor Telepon");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 27, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(lUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(40, 40, 40))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lNoTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfNoTelepon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(tfPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(tfUsername, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(27, 27, 27))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNoTelepon, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(tfNoTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(126, 126, 126))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfNoTeleponFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNoTeleponFocusGained
        // TODO add your handling code here:
        if (tfNoTelepon.getForeground()==Color.GRAY){
            tfNoTelepon.setText("");
            tfNoTelepon.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tfNoTeleponFocusGained

    private void tfNoTeleponFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNoTeleponFocusLost
        // TODO add your handling code here:
        if (tfNoTelepon.getText().equals("")){
            tfNoTelepon.setText("ex: 081234567890");
            tfNoTelepon.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_tfNoTeleponFocusLost

    private void tfNoTeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNoTeleponActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tfNoTeleponActionPerformed

    private void tfUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUsernameFocusGained
        // TODO add your handling code here:
        if (tfUsername.getText().equals("ex: Robert213")){
            tfUsername.setText("");
            tfUsername.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tfUsernameFocusGained

    private void tfUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUsernameFocusLost
        // TODO add your handling code here:
        if (tfUsername.getText().equals("")){
            tfUsername.setText("ex: Robert213");
            tfUsername.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_tfUsernameFocusLost

    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsernameActionPerformed

    private void tfPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPasswordFocusGained
        // TODO add your handling code here:
        if (tfPassword.getForeground()==Color.GRAY){
            tfPassword.setText("");
            tfPassword.setForeground(Color.BLACK);
            tfPassword.setEchoChar('●');
        }
    }//GEN-LAST:event_tfPasswordFocusGained

    private void tfPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPasswordFocusLost
        // TODO add your handling code here:
        if (tfPassword.getText().equals("")){
            tfPassword.setText("ex: 123qweASD");
            tfPassword.setForeground(Color.GRAY);
            tfPassword.setEchoChar((char)0);
        }
    }//GEN-LAST:event_tfPasswordFocusLost

    private void tfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPasswordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            if(tfUsername.getForeground()==Color.BLACK&&
               tfPassword.getForeground()==Color.BLACK&&
               tfNoTelepon.getForeground()==Color.BLACK&&
               taAlamat.getForeground()==Color.BLACK)
            {   
                assert (tfNoTelepon.getText()).matches("\\d{10,13}") : JOptionPane.showOptionDialog(null, "Nomor Telepon tidak valid", "Message", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
                assert (tfPassword.getText()).length()>=8 : JOptionPane.showOptionDialog(null, "Password kurang dari 8", "Message", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
                assert DATA.listGudang.stream().anyMatch(t -> taAlamat.getText().toLowerCase().contains(t.getKota().toLowerCase())) : JOptionPane.showOptionDialog(null, "Layanan belum tersedia di kota anda", "Message", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
                if (!jLabel1.getText().toLowerCase().contains("edit")){
                    assert !DATA.listAkun.stream().anyMatch(t -> t instanceof Pengirim && t.getUsername().equalsIgnoreCase(tfUsername.getText())) : JOptionPane.showOptionDialog(null, "Username sudah ada", "Message", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
                    DATA.addDATA(pengirim);
                }
                pengirim.setUsername(tfUsername.getText());
                pengirim.setPassword(tfPassword.getText());
                pengirim.setNoHp(tfNoTelepon.getText());
                pengirim.setAlamat(taAlamat.getText());
                DATA.updateDATA(pengirim);
                switch (jLabel1.getText()) {
                    case "Edit User":
                        JOptionPane.showMessageDialog(this, "Berhasil diperbarui");
                        GUIMenuAdmin.showTable();
                        break;
                    case "Register User":
                        JOptionPane.showMessageDialog(this, "Registrasi berhasil");
                        break;
                    case "Edit Profil":
                        JOptionPane.showMessageDialog(this, "Berhasil diperbarui");
                        GUILogin.tfUsername.setText(pengirim.getUsername());
                        GUILogin.tfPassword1.setText(pengirim.getPassword());
                        GUIMenuPengirim.jLabel1.setText("Selamat datang, "+pengirim.getUsername());
                        GUIMenuPengirim.loadData();
                        break;
                }
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Format salah atau belum diisi");
            }
        } catch (HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, "Register gagal");
        } catch (AssertionError e){}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void taAlamatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_taAlamatFocusLost
        // TODO add your handling code here:
        if (taAlamat.getText().equals("")){
            taAlamat.setText("ex: Jalan Buah Batu No.02, RT 09 RW 06, Lengkong, Bojongsoang");
            taAlamat.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_taAlamatFocusLost

    private void taAlamatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_taAlamatFocusGained
        // TODO add your handling code here:
        if (taAlamat.getForeground()==Color.GRAY){
            taAlamat.setText("");
            taAlamat.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_taAlamatFocusGained

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogEditDaftarPengirim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        /*java.awt.EventQueue.invokeLater(() -> {
            DialogEditDaftarPengirim dialog = new DialogEditDaftarPengirim(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private static javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lAlamat;
    private javax.swing.JLabel lNoTelepon;
    private javax.swing.JLabel lPassword;
    private javax.swing.JLabel lUsername;
    private javax.swing.JTextArea taAlamat;
    private javax.swing.JTextField tfNoTelepon;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
