/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiClass;

import OOP.Users.Pengirim;
import OOP.Users.Kurir;
import DAO.DATA;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author roni
 */
public class GUILogin extends javax.swing.JFrame {

    /**
     * Creates new form GUILoginForm2
     * @throws java.sql.SQLException
     */
    
    public GUILogin() throws SQLException {
        initComponents();
        DATA.loadDATA();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        lUsername = new javax.swing.JLabel();
        tfPassword1 = new javax.swing.JPasswordField();
        lPassword = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 275));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN");

        tfUsername.setForeground(java.awt.Color.gray);
        tfUsername.setText("Masukkan Username");
        tfUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfUsernameFocusLost(evt);
            }
        });
        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });

        lUsername.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lUsername.setText("Username");

        tfPassword1.setForeground(java.awt.Color.gray);
        tfPassword1.setText("Masukkan Password");
        tfPassword1.setEchoChar('\u0000');
        tfPassword1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPassword1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPassword1FocusLost(evt);
            }
        });
        tfPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPassword1ActionPerformed(evt);
            }
        });

        lPassword.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lPassword.setText("Password");

        jButton1.setText("Masuk");
        jButton1.setToolTipText("");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(tfPassword1))))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfPassword1)
                    .addComponent(lPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUsernameFocusGained
        // TODO add your handling code here:
        if (tfUsername.getText().equals("Masukkan Username")){
            tfUsername.setText("");
            tfUsername.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tfUsernameFocusGained

    private void tfUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUsernameFocusLost
        // TODO add your handling code here:
        if (tfUsername.getText().equals("")){
            tfUsername.setText("Masukkan Username");
            tfUsername.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_tfUsernameFocusLost

    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsernameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            if (StartMenu.pilih.equals("admin")&&DATA.admin.getUsername().equals(tfUsername.getText())&&DATA.admin.getPassword().equals(tfPassword1.getText())){
                new GUIMenuAdmin().setVisible(true);
                dispose();
            } else if(StartMenu.pilih.equals("pengirim")&&DATA.listAkun.stream().anyMatch((t) -> t.getUsername().equals(tfUsername.getText())&&t.getPassword().equals(tfPassword1.getText())&&t instanceof Pengirim)) {
                new GUIMenuPengirim().setVisible(true);
                dispose();
            } else if(StartMenu.pilih.equals("kurir")&&DATA.listAkun.stream().anyMatch((t) -> t.getUsername().equals(tfUsername.getText())&&t.getPassword().equals(tfPassword1.getText())&&t instanceof Kurir)) {
                new GUIMenuKurir().setVisible(true);
                dispose();
            } else {
                throw new Exception("Username atau Password salah");
            }
            
        } catch (SQLException e){
            JOptionPane.showMessageDialog(this, "Login gagal");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new StartMenu().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tfPassword1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPassword1FocusGained
        // TODO add your handling code here:
        if (tfPassword1.getText().equals("Masukkan Password")){
            tfPassword1.setText("");
            tfPassword1.setForeground(Color.BLACK);
            tfPassword1.setEchoChar('●');
        }
    }//GEN-LAST:event_tfPassword1FocusGained

    private void tfPassword1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPassword1FocusLost
        // TODO add your handling code here:
        if (tfPassword1.getText().equals("")){
            tfPassword1.setText("Masukkan Password");
            tfPassword1.setForeground(Color.GRAY);
            tfPassword1.setEchoChar((char)0);
        }
    }//GEN-LAST:event_tfPassword1FocusLost

    private void tfPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPassword1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lPassword;
    private javax.swing.JLabel lUsername;
    public static javax.swing.JPasswordField tfPassword1;
    public static javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
